# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s = "Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet = "Earth"
diameter = 12747
print('The diameter of {} is {} kilometers.' .format(planet,diameter))

The diameter of Earth is 12747 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'traget':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

<class 'KeyError'>: 'target'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
array=np.zeros(10)
print(array)

<class 'NameError'>: name 'np' is not defined

In [6]:
import numpy as np
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [7]:
import numpy as np
x=np.arange(20,36)
y=(x%2==0)
z=x[y]
print(z)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
x=np.arange(0,9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [9]:
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.concatenate((a,b))
print(x)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [10]:
dataframe=np.random.randint(15,size=(3,2))
print(dataframe)

[[ 0 12]
 [ 8 14]
 [14  3]]


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [11]:
import pandas as nd
sdate=date(2023,1,1)
edata=date(2023,2,10)
pd.date_range(sdata,edata-timelta(days=1),freq='d')

<class 'NameError'>: name 'date' is not defined

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [12]:
lists=[[1,'aaa',22],[2,'bb',25],[3,'cc',24]]
dataframe=pd.DataFrame(lists)
print(dataframe)

<class 'NameError'>: name 'pd' is not defined