# Basic Python

## 1. Split this string

In [ ]:
s="Hi there Sam!"

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [22]:
planet = "Earth"
diameter = 12742
print( 'the diameter of {} is {} kilometers.' .format(planet,diameter))

the diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [21]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [23]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
import numpy as np
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [11]:
import numpy as np
x=np.arange(20,36)
y=(x%2==0)
z=x[y]
print(z)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
x=np.arange(0,9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
x=np.concatenate((a,b))
print(x)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [14]:
dataframe=np.random.randint(15,size=(3,2))
print(dataframe)

[[ 3 12]
 [ 4  0]
 [11  5]]


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [34]:
import pandas as pd 
from datetime import datetime ,timedelta
sdate =date(2023,1,1)
edate = date(2023, 2, 10)
pd.date_range(sdate,edate-timedelta(days=1),freq='d')

<class 'NameError'>: name 'date' is not defined

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [31]:

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
dateframe=pd.DataFrame(lists)
print(dataframe)

[[ 3 12]
 [ 4  0]
 [11  5]]
